#cloud-config
autoinstall:
  version: 1
  interactive-sections:
    - storage
  identity:
    realname: Omie Experience
    hostname: omie-temp
    username: omiexperience
    password: '$6$3E2cR0kN9oWblSVO$KiGsxAShHRSAaQ3k81LoJXSyMvBxuJUugy2p7.9xXH76uQOKUTLgh5odn4Fu1fABIqwk0aoVs3rKaI7Ulp14F0'
  locale: pt_BR.UTF-8
  keyboard:
    layout: br
  timezone: America/Sao_Paulo
  packages:
    - curl
    - wget
    - git
    - unzip
    - apt-transport-https
    - tpm2-tools
    - cryptsetup-bin
    - initramfs-tools
    - timeshift
    - chrony
  snaps:
    - name: slack
      channel: stable
      classic: true
  updates: all
  shutdown: reboot
  late-commands:
    - curtin in-target -- bash -c "echo 'server gps.ntp.br iburst' > /etc/chrony/chrony.conf"
    - curtin in-target -- systemctl restart chrony
    - curtin in-target -- wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | gpg --dearmor -o /usr/share/keyrings/google-chrome.gpg
    - curtin in-target -- bash -c "echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/google-chrome.gpg] http://dl.google.com/linux/chrome/deb/ stable main' > /etc/apt/sources.list.d/google-chrome.list"
    - curtin in-target -- apt-get update
    - curtin in-target -- apt-get install -y google-chrome-stable
    - curtin in-target -- mkdir -p /etc/opt/chrome/policies/forced
    - ["curtin", "in-target", "--", "bash", "-c", "echo '{\"ExtensionInstallForcelist\": [\"mclkkofklkfljcocdinagocijianpkik;https://clients2.google.com/service/update2/crx\", \"inomeicfmomofachclnbeeidmbiinean;https://clients2.google.com/service/update2/crx\"]}' > /etc/opt/chrome/policies/forced/external_extensions.json"]
    - curtin in-target -- wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb -P /tmp
    - curtin in-target -- dpkg -i /tmp/chrome-remote-desktop_current_amd64.deb || apt-get install -f -y
    - curtin in-target -- mkdir -p /usr/share/backgrounds/omie
    - curtin in-target -- curl -sL "https://raw.githubusercontent.com/ServiceITomie/Ubuntu_Autopilot/main/wallpaper-omie.jpg" -o /usr/share/backgrounds/omie/wallpaper-omie.jpg
    - curtin in-target -- bash -c "echo '[org.gnome.desktop.background]' > /usr/share/glib-2.0/schemas/10_omie_wallpaper.gschema.override"
    - curtin in-target -- bash -c "echo \"picture-uri='file:///usr/share/backgrounds/omie/wallpaper-omie.jpg'\" >> /usr/share/glib-2.0/schemas/10_omie_wallpaper.gschema.override"
    - curtin in-target -- bash -c "echo \"picture-uri-dark='file:///usr/share/backgrounds/omie/wallpaper-omie.jpg'\" >> /usr/share/glib-2.0/schemas/10_omie_wallpaper.gschema.override"
    - curtin in-target -- glib-compile-schemas /usr/share/glib-2.0/schemas/
    - curtin in-target -- timeshift --create --comments "Snapshot Inicial TI" --tags D
